export const FETCH_ARTICLES_REQUEST= 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS= 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE= 'FETCH_ARTICLES_FAILURE';

export const PUT_ARTICLE_REQUEST= 'PUT_ARTICLE_REQUEST';
export const PUT_ARTICLE_SUCCESS= 'PUT_ARTICLE_SUCCESS';
export const PUT_ARTICLE_FAILURE= 'PUT_ARTICLE_FAILURE';

export const FETCH_COMMENTS_REQUEST= 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS= 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE= 'FETCH_COMMENTS_FAILURE';